### ISSUE TITLE
SparkException: A master URL must be set in your configuration

### ISSUE THREAD

**Issue by nano4711** [openforce/spark-mllib-scala-play#1]
After a fresh git clone und switching to develop branch I get the following error when I try to access http://localhost:9000/

    2015-11-11 10:04:08,019 - [warn] o.a.h.u.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
    2015-11-11 10:04:08,075 - [error] o.a.s.SparkContext - Error initializing SparkContext.
    org.apache.spark.SparkException: A master URL must be set in your configuration
      at org.apache.spark.SparkContext.<init>(SparkContext.scala:394) [spark-core_2.11-1.5.1.jar:1.5.1]
      at org.apache.spark.SparkContext.<init>(SparkContext.scala:112) [spark-core_2.11-1.5.1.jar:1.5.1]
      at org.apache.spark.SparkContext$$FastClassByGuice$$119109b9.newInstance(<generated>) [guice-4.0.jar:1.5.1]
      at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) [guice-4.0.jar:na]
      at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) [guice-4.0.jar:na]
    2015-11-11 10:04:08,098 - [error] application -

    ! @6o4ml9c9d - Internal server error, for (GET) [/] ->

    play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ProvisionException: Unable to provision, see the following errors:

    1) Error injecting constructor, org.apache.spark.SparkException: A master URL must be set in your configuration
      at org.apache.spark.SparkContext.<init>(SparkContext.scala:112)
      while locating org.apache.spark.SparkContext
        for parameter 1 at controllers.Application.<init>(Application.scala:23)
      at controllers.Application.class(Application.scala:23)
      while locating controllers.Application

    1 error]]
      at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
      at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
      at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:50) [play-server_2.11-2.4.2.jar:2.4.2]
      at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:59) [play-server_2.11-2.4.2.jar:2.4.2]
      at play.core.server.Server$$anonfun$getHandlerFor$4.apply(Server.scala:57) [play-server_2.11-2.4.2.jar:2.4.2]
    Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

    1) Error injecting constructor, org.apache.spark.SparkException: A master URL must be set in your configuration
      at org.apache.spark.SparkContext.<init>(SparkContext.scala:112)
      while locating org.apache.spark.SparkContext
        for parameter 1 at controllers.Application.<init>(Application.scala:23)
      at controllers.Application.class(Application.scala:23)
      while locating controllers.Application

    1 error
      at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:na]
      at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
      at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11-2.4.2.jar:2.4.2]
      at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$11.apply(Routes.scala:179) ~[na:na]
      at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$1$$anonfun$apply$11.apply(Routes.scala:179) ~[na:na]
    Caused by: org.apache.spark.SparkException: A master URL must be set in your configuration
      at org.apache.spark.SparkContext.<init>(SparkContext.scala:394) ~[spark-core_2.11-1.5.1.jar:1.5.1]
      at org.apache.spark.SparkContext.<init>(SparkContext.scala:112) ~[spark-core_2.11-1.5.1.jar:1.5.1]
      at org.apache.spark.SparkContext$$FastClassByGuice$$119109b9.newInstance(<generated>) ~[guice-4.0.jar:1.5.1]
      at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[guice-4.0.jar:na]
      at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) ~[guice-4.0.jar:na]

**Comment by Juliana123** [comment]
??????? ;-)






----
Juliana Kund | Projektmanagement

openForce Information Technology GesmbH
Franzensbrückenstraße 5/5
1020 Wien

web: openforce.com
mail: juliana.kund@openforce.com
tel: +43 1 319 1775 214

————
Geschäftsführung: Otto Meinhart, Gerhard Hipfinger
Firmenbuch: Handelsgericht Wien, Sitz Wien, FN 218366b
