### ISSUE TITLE
Not able to perform OAuth login

### ISSUE THREAD

**Issue by nano4711** [openforce/spark-mllib-scala-play#23]
With the current develop branch I cannot login via OAuth. I get the following error:

    2015-12-08 19:26:02,541 - [warn] o.a.h.i.c.DefaultHttpClient - Authentication error: Unable to respond to any of these challenges: {oauth=www-    authenticate: OAuth realm="https://api.twitter.com"}
    2015-12-08 19:26:02,543 - [error] application -

    ! @6oce0039p - Internal server error, for (GET) [/authenticate] ->

    play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[OAuthNotAuthorizedException: Authorization failed (server replied with a     401). This can happen if the consumer key was not correct or the signatures did not match.]]
      at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.4.jar:2.4.4]
      at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.4.jar:2.4.4]
      at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.4.jar:2.4.4]
      at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.4.jar:2.4.4]
      at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.4.jar:2.4.4]
    Caused by: oauth.signpost.exception.OAuthNotAuthorizedException: Authorization failed (server replied with a 401). This can happen if the     consumer key was not correct or the signatures did not match.
      at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:243) ~[signpost-core-1.2.1.2.jar:na]
      at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193) ~[signpost-core-1.2.1.2.jar:na]
      at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:74) ~[signpost-core-1.2.1.2.jar:na]
      at play.api.libs.oauth.OAuth.retrieveRequestToken(OAuth.scala:36) ~[play-ws_2.11-2.4.4.jar:2.4.4]
      at controllers.Twitter$$anonfun$authenticate$1$$anonfun$apply$2.apply(Twitter.scala:38) ~[classes/:na]

**Comment by nano4711** [comment]
I uses 127.0.0.1:9000 and used http://127.0.0.1:9000/authenticate as callback URL in the Twitter settings for the application.

**Comment by cmacher** [comment]
Sorry I have updated some names of the Twitter config to match the official naming. I was just about to send the info email. If you have local.conf the access tokens should be configured like in application.conf.
```
  consumer {
    key = ""
    secret = ""
  }

  access {
    token = ""
    secret = ""
  }
```
